name: vachanapetty
description: A new vachanapetty app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.4+15

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path: any
  sqflite: ^2.3.0
  freezed_annotation: ^3.1.0
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  flutter_svg: ^2.3.0
  

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  build_runner: ^2.10.4
  analyzer: ^8.0.0
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/vachanapetty.db

  fonts:
    - family: Noto Serif Malayalam
      fonts:
        - asset: assets/fonts/NotoSerifMalayalam/NotoSerifMalayalam-Medium.ttf

    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel/CinzelDecorative-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cinzel/CinzelDecorative-Bold.ttf
          weight: 700

    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EbGaramond/EBGaramond.ttf

  
        
    
